theme: jekyll-theme-architect
title: welcome to lixu's homepage!
![Plasmonic](https://cn.bing.com/images/search?view=detailV2&ccid=RUsuzl6x&id=D47280DFFC0E3C7D736597D6ACF26D794A972E98&thid=OIP.RUsuzl6xzsMO0hyPxDpyzwHaEE&mediaurl=https%3a%2f%2feng.libretexts.org%2f%40api%2fdeki%2ffiles%2f325%2fElectron_Cloud.jpg%3frevision%3d1&exph=290&expw=527&q=plasmon&simid=608055717632411961&ck=4CF7C7FFAF5B31D83922B131D35FD83A&selectedIndex=17&FORM=IRPRST&ajaxhist=0)
